# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.23

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake-dir/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake-dir/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/d/Work/Code/cpp/oop/object-serialization

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/d/Work/Code/cpp/oop/object-serialization

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-dir/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake-dir/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/d/Work/Code/cpp/oop/object-serialization/CMakeFiles /mnt/d/Work/Code/cpp/oop/object-serialization//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/d/Work/Code/cpp/oop/object-serialization/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named test_binary

# Build rule for target.
test_binary: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_binary
.PHONY : test_binary

# fast build rule for target.
test_binary/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_binary.dir/build.make CMakeFiles/test_binary.dir/build
.PHONY : test_binary/fast

#=============================================================================
# Target rules for targets named test_xml

# Build rule for target.
test_xml: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_xml
.PHONY : test_xml

# fast build rule for target.
test_xml/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_xml.dir/build.make CMakeFiles/test_xml.dir/build
.PHONY : test_xml/fast

include/thirdparty/tinyxml2.o: include/thirdparty/tinyxml2.cpp.o
.PHONY : include/thirdparty/tinyxml2.o

# target to build an object file
include/thirdparty/tinyxml2.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_xml.dir/build.make CMakeFiles/test_xml.dir/include/thirdparty/tinyxml2.cpp.o
.PHONY : include/thirdparty/tinyxml2.cpp.o

include/thirdparty/tinyxml2.i: include/thirdparty/tinyxml2.cpp.i
.PHONY : include/thirdparty/tinyxml2.i

# target to preprocess a source file
include/thirdparty/tinyxml2.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_xml.dir/build.make CMakeFiles/test_xml.dir/include/thirdparty/tinyxml2.cpp.i
.PHONY : include/thirdparty/tinyxml2.cpp.i

include/thirdparty/tinyxml2.s: include/thirdparty/tinyxml2.cpp.s
.PHONY : include/thirdparty/tinyxml2.s

# target to generate assembly for a file
include/thirdparty/tinyxml2.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_xml.dir/build.make CMakeFiles/test_xml.dir/include/thirdparty/tinyxml2.cpp.s
.PHONY : include/thirdparty/tinyxml2.cpp.s

test_binary.o: test_binary.cpp.o
.PHONY : test_binary.o

# target to build an object file
test_binary.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_binary.dir/build.make CMakeFiles/test_binary.dir/test_binary.cpp.o
.PHONY : test_binary.cpp.o

test_binary.i: test_binary.cpp.i
.PHONY : test_binary.i

# target to preprocess a source file
test_binary.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_binary.dir/build.make CMakeFiles/test_binary.dir/test_binary.cpp.i
.PHONY : test_binary.cpp.i

test_binary.s: test_binary.cpp.s
.PHONY : test_binary.s

# target to generate assembly for a file
test_binary.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_binary.dir/build.make CMakeFiles/test_binary.dir/test_binary.cpp.s
.PHONY : test_binary.cpp.s

test_xml.o: test_xml.cpp.o
.PHONY : test_xml.o

# target to build an object file
test_xml.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_xml.dir/build.make CMakeFiles/test_xml.dir/test_xml.cpp.o
.PHONY : test_xml.cpp.o

test_xml.i: test_xml.cpp.i
.PHONY : test_xml.i

# target to preprocess a source file
test_xml.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_xml.dir/build.make CMakeFiles/test_xml.dir/test_xml.cpp.i
.PHONY : test_xml.cpp.i

test_xml.s: test_xml.cpp.s
.PHONY : test_xml.s

# target to generate assembly for a file
test_xml.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_xml.dir/build.make CMakeFiles/test_xml.dir/test_xml.cpp.s
.PHONY : test_xml.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... test_binary"
	@echo "... test_xml"
	@echo "... include/thirdparty/tinyxml2.o"
	@echo "... include/thirdparty/tinyxml2.i"
	@echo "... include/thirdparty/tinyxml2.s"
	@echo "... test_binary.o"
	@echo "... test_binary.i"
	@echo "... test_binary.s"
	@echo "... test_xml.o"
	@echo "... test_xml.i"
	@echo "... test_xml.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

